site-description: >-
  ג׳אפו יפני בהרכבה אישית. המקום בו אוכל אסייתי פוגש את הטעם הישראלי ויוצר מפגש
  טעמים ייחודי, מגוון ונהדר
facebook: 'https://www.facebook.com/japoit/'
instagram: 'https://www.instagram.com/japoisrael/'
phone: 039441716
copyright: '© 2017, Japo. Designed by Studio Bagaz'''
