site-description: >-
  ג׳אפו יפני בהרכבה אישית. המקום בו אוכל אסייתי פוגש את הטעם הישראלי ויוצר מפגש
  טעמים ייחודי, מגוון ונהדר
facebook: 'https://www.facebook.com/japoit/'
instagram: 'https://instagram.com'
phone: בקרוב
copyright: '© 2017, Japo. Designed by Studio Bagaz'''
